.github/workflows/add_assignee_to_pr.yml

add_assignee_to_pr.yml に permissions を追加します。
PR #3 で追加されるはずが、結果的に追加されなかったようです。
🔗 https://github.com/route06/actions/pull/3/commits
1. 8cd205e2f8c3a0a01745b45bac20719240886545
* 関係ない変更
1. 5a3edc583aea1eb6591c528fed5e60bd7a5e0b2d
* _add-assignee-to-pr.yml から permissions 設定削除 ← ❓
* add-assignee-to-pr.yml に permissions 設定追加 ✅
1. cb91130df02e1ce2ac21ca3cd5fee5e01806d355
* 関係ない変更
1. bf99edc3db7fdc3fe36ffa69206867f4a7006a66
* 関係ない変更
1. f2eb165967e60290296f737565fca65b2ebc11c4
* add-assignee-to-pr.yml を setup-pr.yml にリネーム ← ここ ⚠️
~~https://github.com/technote-space/assign-author/pull/261 がマージされれば、permissions は不要です。~~
良く見たら、README.md の変更なので間違い。

Fix permissions of add_assignee_to_pr.yml

---

.github/workflows/my_release.yml
README.md
docs/adr/004-tagprの導入.md

PR https://github.com/route06/actions/pull/20 によって、Release PR が無事作られた。
* https://github.com/route06/actions/pull/21
本 PR では、以下を実装する。
* Release 時に v2 等の git tag が最新の v2.Y.Z を指すように書き換える
* 今までは手動でのリリース後に、ローカルでの git 操作で更新していた
* README.md にリリースフローを追加する

Release 時に v2 等の git tag が最新の v2.Y.Z を指すように書き換える

---

.github/workflows/my_release.yml

Release PR https://github.com/route06/actions/pull/21 のマージをトリガーに発動した Release workflow で、以下のエラーが発生した。
🔗 https://github.com/route06/actions/actions/runs/9183827570/job/25255161968
> Run git tag -f v2 v2.0.2
> 　git tag -f v2 v2.0.2
> 　shell: /usr/bin/bash -e {0}
> 　env:
> 　　MAJOR_VERSION: v2
> fatal: Failed to resolve 'v2.0.2' as a valid ref.
> Error: Process completed with exit code 128.
v2 タグの更新時のエラー。本 PR ではこれを修正する。

Fix release workflow

---

.github/workflows/my_release.yml

確率は低いと思いますが、Release workflow が同時実行されると意図しないことが起こりそうなので、対策しました。
参考情報:
[コンカレンシーの使用 \- GitHub Docs](https://docs.github.com/ja/actions/using-jobs/using-concurrency)

Avoid concurrent release workflow

---

.github/release.yml

release.ymlのセクションとして `Maintenance 🧑‍💻` を追加し、 https://github.com/route06/actions/labels/maintenance label を含めるようにしました。
https://github.com/route06/actions/pull/31 は今Other Changesにまとめられていますが、利用者に関係ない変更であり、このリポジトリのメンテナンスであることを伝えられると良さそうなためです。

maintenance: change section and add label for release.yml

---

.github/workflows/gh_discussion_comment_to_slack.yml
.github/workflows/my_release.yml
.github/workflows/my_test.yml
.github/workflows/notify_slack_on_ci_failed.yml

ref. https://github.com/route06/actions/issues/4
セキュアな Reusable Workflow を提供し続けるために、このリポジトリの CI に [rhysd/actionlint](https://github.com/rhysd/actionlint) を導入します。
トリガーは以下のとおりです。
* main ブランチへの commit 追加
* Pull request 作成時
`rhysd/actionlint` は [reviewdog/action-actionlint](https://github.com/reviewdog/action-actionlint) を介して使用します。actionlint のエラーは https://github.com/route06/actions/pull/35#discussion_r1639539282 のように、Pull request のコメントとして指摘されます。
actionlint で指摘があった既存の workflow も 29fcf0a0dc2b65f04d67e8822035607a4d96da7a...26c5a95d6d97eb45bb54692e83e36ef0611fe9f1 で修正しています。
* [GitHub Actions のワークフローをチェックする actionlint をつくった \- はやくプログラムになりたい](https://rhysd.hatenablog.com/entry/2021/07/11/214313)
* https://github.com/rhysd/actionlint
* [社内用GitHub Actionsのセキュリティガイドラインを公開します \| …

Introduce actionlint workflow

---

.github/workflows/my_test.yml

リポジトリにマージキューを設定しました！このPRのマージボタンも以下のように `Merge when ready` と表記が変わっています。
これにより、 `Merge when ready` を押すとマージキューに追加され、mainブランチを取り込んだ状態でCIを実行した後、成功した場合のみmainブランチにマージされます。これにより複数PRの競合があった際にmainブランチが不正な状態になることを防ぐことができます。
マージキュー上でのみ失敗するCIをデバッグとして用意するのは難しいのですが、すでに社内で運用されている設定内容と同一のためおそらく問題はないと思っています。以下の記事で掲載しているスクリーンショットと同一です:
[モノレポでマージキューと必須ステータスチェックを運用するためのTips - ROUTE06 Tech Blog](https://tech.route06.co.jp/entry/2024/06/12/121511)
このPRのマージ時に、マージキューの挙動を録画してPRのコメントに残す予定です。
<details><summary>リポジトリのSettingsでのブランチ保護ルールの設定内容</summary>
<p>
</p>
</details>

maintenance: Setup merge queue and remove push event

---

.github/workflows/gh_discussion_comment_to_slack.yml

https://github.com/route06/actions/pull/41 の 6d7829e66043eda3f84d2f452c0eb8b2539ec496 に問題があった。ディスカッションタイトルに半角スペースが含まれていると、jq parse error が発生する。
Before（jq parse error が発生する）:
```
--arg title "*<https://github.com/org/repo/discussions/123#discussioncomment-9876543|Comment on #123 "2024/06/18 ミーティングタイトル">*"
```
After（jq parse error が修正される）:
```
--arg title "*<https://github.com/org/repo/discussions/123#discussioncomment-9876543|Comment on #123 2024/06/18 ミーティングタイトル>*"
```
toJSON することで `ミーティングタイトル` が `"ミーティングタイトル"` になる気がするので、toJSON を削除した。
https://github.com/route06/actions/pull/41 の前の https://github.com/route06/actions/pull/35 で、環境変数を使ったことで、shell injection の問題は解決できたはず。
そもそも参考にした 31 行目の記事で toJSON は使っていない。
[【GitHub Actions】GitHub DiscussionsをSlackで通知する \- HRBrain …

Fix gh_discussion_comment_to_slack.yml part2

---

.github/workflows/add_assignee_to_pr.yml
.github/workflows/my_setup_pr.yml

🔗 https://github.com/route06/actions/actions/runs/9560315162
> [Invalid workflow file: .github/workflows/my_setup_pr.yml#L8](https://github.com/route06/actions/actions/runs/9560315162/workflow)
> The workflow is not valid. .github/workflows/my_setup_pr.yml (Line: 8, Col: 3): Error calling workflow 'route06/actions/.github/workflows/add_assignee_to_pr.yml@5622884443da96cddf8ac859ef947f85551e80ed'. The nested job 'add-assignee-to-pr' is requesting 'pull-requests: write', but is only allowed 'pull-requests: none'.
今度は https://github.com/route06/actions/pull/38 の 7d387d8736822a2535fa391399b9eda001b65abb でのエンバグです 🙇
上記エラーメッセージによると、ネストされた子供の workflow で要求する permissions は、呼び元の親 workflow で明示的に指定する必要があるそうです。知りませんでしたorz

fix missing permission for my_setup_pr.yml

---

.github/workflows/add_assignee_to_pr.yml
.github/workflows/my_test.yml
.github/workflows/notify_slack_on_ci_failed.yml
docs/adr/005-サードパーティのgithub-actionsのバージョンをfull-changeset-hashで固定する.md
docs/adr/README.md

サードパーティの GitHub Actions のバージョンを Full Changeset Hash での固定に変更する。
```yaml
- uses: owner/action-name@v1.0.0
- uses: owner/action-name@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v1.0.0
```
👈 の GitHub Actions について、変更した
| Action name | Verified creator | Next action |
|---|:---:|---|
| [actions/checkout](https://github.com/marketplace/actions/checkout) | ✅ | Verified creator なので移行しない |
| [actions/setup-java](https://github.com/marketplace/actions/setup-java-jdk) | ✅ | Verified creator なので移行しない |
| [dorny/paths-filter](https://github.com/marketplace/actions/paths-changes-filter) | | 移行済なので何もしない |
| [github/codeql-action/analyze](https://github.com/github/codeql-action/tree/main/analyze)[^1] |  | Verified creator の明記はないが GitHub 製なので移行しない |
| …

Use full changeset hash for 3rd-party GitHub Actions

---

.github/workflows/my_release.yml
.github/workflows/my_test.yml

tagprによるリリースPRの作成時、使用するトークンをGitHub App経由のトークンにしました。
https://github.com/route06/actions/pull/40 でマージキューを導入し、それによりPRは必須ステータスチェックを通さないとマージできなくなりました。人間によって作成するPRであれば問題ありませんが、tagprによるリリースPRはデフォルトのトークンではCIが発火せず、必須ステータスチェックが通らなくなってしまいました。
これをGitHub App経由のトークンにすることでCIが発火するようになる想定です。
動作確認用のデバッグコミットとして別のCIでGitHub App経由のトークンを利用し、取り急ぎContentの取得(= actions/checkoutによるチェックアウト)ができることを確認しました。
ref: https://github.com/route06/actions/actions/runs/9710893014/job/26802526164
tagprが行うのはPRの作成とContentの更新であり、後者の確認ができた形です。前者についてはこのPRのマージ後作成されるPRで確認できればと思います。
- このPRをマージ後作成されるリリースPRで以下を確認する
- CIが発火し、テストが実行され、必須ステータスチェックが通っていること
- CHANGELOGの更新コミットが成功していること

maintenance: use github app token

---

.github/workflows/create_discussion.yml

[この辺](https://github.com/route06/actions/pull/52#pullrequestreview-2159628912) の修正を入れています。
- description_template_path の中身が空の時はデフォルトコンテンツを入れる
- 72cf002de0efec708da0cf06e09399f49767a94c
- ~~週次だけでなく、日次や月次のdiscussion作成でも使えるように、discussion作成だけにworkflowの処理を絞り、日付つきタイトルは呼び出し元で設定する~~
- ~~83426dc9edc2e23f8e5e3ed188c50e522453bb5f~~
- ~~Starter Workflowとしてパターンを作成する想定~~
- ~~7f3562ed381ddaf38bb5815bdb791a64cba7372e~~
打ち消し線部分は別PRとする。

workflows/create_discussion.yml で空のテンプレートファイルを許容する

---

.github/workflows/create_gh_discussion.yml
README.md

💡 feature ブランチへの PR です。
"discussion" が GitHub Discussion を指すことは自明**ではない**ので、リネームしました。 1461a4f1adfe0b5c66c81c0a57161e47acfe19a6
※ [gh CLI](https://github.com/cli/cli) があるので、gh という省略名は許容されるかなと思っています。
一度 create_gh_discussion.yml という名前でリリースすると、リネームのような破壊的な変更をした時に v3 にメジャーアップデートしないといけなくなるので、現時点で変更したい気持ちがあります。
ついでに `@usage` の細かい間違いも修正しました。 bb3448fd752f45f880fb497506ceb8eb0f3f7dfd
参考: [修正後の「利用可能なWorkflow」](https://github.com/route06/actions/tree/bb3448fd752f45f880fb497506ceb8eb0f3f7dfd?tab=readme-ov-file#%E5%88%A9%E7%94%A8%E5%8F%AF%E8%83%BD%E3%81%AAworkflow)
そういう意味では get_last_discussion_url.yml という名前に後悔...。

Rename create_discussion.yml to create_gh_discussion.yml

---

.github/workflows/my_release.yml

🔗 https://github.com/route06/actions/pull/55#pullrequestreview-2162111686
> 別件になるが、[Create GitHub App Token は Verified creator](https://github.com/marketplace/actions/create-github-app-token) なので、メジャーバージョン指定でよいだろう（[ADR](https://github.com/route06/actions/blob/v2.1.7/docs/adr/005-%E3%82%B5%E3%83%BC%E3%83%89%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3%E3%81%AEgithub-actions%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92full-changeset-hash%E3%81%A7%E5%9B%BA%E5%AE%9A%E3%81%99%E3%82%8B.md)）。別で PR 作る。

Pin actions/create-github-app-token to major version

---

.github/workflows/calc_next_date.yml
.github/workflows/create_gh_discussion.yml
README.md

@TomckySan PR https://github.com/route06/actions/pull/61 への PR です
* get_next_scheduled_date.yml に `scheduled` というコンテキストは必要ないと感じたので、calc_next_date.yml にリネームしました
* calc_next_date.yml は「現在の時刻と入力された条件から、次の日付を計算する」という役割に徹する。何に使われるかは知らない。というニュアンスです
* それにともない、全体的に `scheduled` という文字列を削除しました
* create_gh_discussion.yml の usage は、calc_next_date.yml を使う方法に更新しました
💡 2024/07/31 13:00 JST 頃に動作確認しました
コード:
https://github.com/masutaka/sandbox/blob/2c3e65603b460d8e60b2a3a4138a6030f70dd74f/.github/workflows/calc_date.yml
結果:
https://github.com/masutaka/sandbox/actions/runs/10173764531/job/28138394137
コード:
https://github.com/masutaka/sandbox/blob/135762e05eeb6fe695054ca18cd8ca95ca8a1f00/.github/workflows/calc_date.yml
結果:
https://github.com/masutaka/sandbox/actions/runs/10173784428/job/28138449726

Rename get_next_scheduled_date.yml to calc_next_date.yml

---

.github/workflows/create_gh_discussion.yml

@TomckySan PR https://github.com/route06/actions/pull/61 への PR です
以下の inputs に対して、category_slug だけ `discussion_` prefix が付いているのは違和感があったので修正しました。
* title
* description_template_path
細かいと言えば細かいですが、リリース後に変更すると破壊的な変更になるため、このタイミングで修正しました。
💡 2024/08/01 13:40 JST 頃に動作確認しました
コード:
https://github.com/masutaka/sandbox/blob/30bf8ea8629e5aef87509f83b161375a9663b23e/.github/workflows/create_discussion.yml
結果:
https://github.com/masutaka/sandbox/actions/runs/10192146455
↓
https://github.com/masutaka/sandbox/discussions/10

Improve input name of create_gh_discussion.yml

---

.github/workflows/add_assignee_to_pr.yml
.github/workflows/calc_next_date.yml
.github/workflows/codeql.yml
.github/workflows/codeql_core.yml
.github/workflows/create_gh_discussion.yml
.github/workflows/get_last_discussion_url.yml
.github/workflows/gh_discussion_comment_to_slack.yml
.github/workflows/my_release.yml
.github/workflows/my_setup_pr.yml
.github/workflows/my_test.yml
.github/workflows/notify_slack_on_ci_failed.yml

(1) 見栄えが良くないので、全ての workflow に `name:` を設定しました。また、`my_*.yml` の workflow は `My ` prefix を付けました（[参考](https://github.com/route06/actions/blob/v2.2.0/docs/adr/003-%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E3%81%AE%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87.md)）。
🔗 https://github.com/route06/actions/actions
(2) ドキュメント中の usage にも `name:` を設定し、見栄えの悪さがユーザーに伝播しないようにしました。
(3) 全体的にドキュメントを改善しました。
f47f04dbdcd84adc52ab9c68c9d32e513c006135 以外は、変更後のファイルを確認するとレビューしやすいかと思います。
* [add_assignee_to_pr.yml](https://github.com/route06/actions/blob/add-name-to-workflows/.github/workflows/add_assignee_to_pr.yml)
* [calc_next_date.yml](https://github.com/route06/actions/blob/add-name-to-workflows/.github/workflows/calc_next_date.yml)
* [codeql.yml](https://github.com/route06/actions/blob/add-name-to-workflows/. …

全ての workflow に `name:` を設定しつつ、reusable workflow のドキュメントを改善する

---

.github/workflows/add_discussion_comment.yml

* 指定した GitHub Discussion ID にコメントを追加する reusable workflow を追加した
* コメントは `comment_template_path` で、ファイルパスを指定する
* 追加したコメントに返信することも可能
* サンプルコード
* https://github.com/masutaka/sandbox/blob/9c9f3dfb9a27f9a3a97a06c78e64dd2d4634ff2f/.github/workflows/create_discussion.yml#L27-L46
* 実行した GitHub Action
* https://github.com/masutaka/sandbox/actions/runs/10822157127
* GitHub Discussion にコメントを追加し、さらにそのコメントに返信した様子
* https://github.com/masutaka/sandbox/discussions/38#discussioncomment-10620406
@TomckySan と話して、下記 PR を私の方でやろうとしました。
* https://github.com/route06/actions/pull/60
ただ、テンプレートファイルで変数を使うのは、初期実装として大きかったので一旦固定コメントにしました。
コメントを何個も追加するユースケースは、matrix 使って add_discussion_comment.yml を何回も実行したほうが良いかも知れません。
* [Running variations of jobs in a workflow \- GitHub …

指定した GitHub Discussion ID に固定コメントを追加する reusable workflow を作成

---

.github/workflows/create_gh_issue.yml

* GitHub Issue を生成する reusable workflow を作成した
* title, description_template_path, assignees, labels を入力可能
* サンプルコード
* https://github.com/masutaka/sandbox/blob/a9f91dd6d9b4611455b9a1bb230f6bf2d5db46d1/.github/workflows/create_issue.yml
* サンプルコードから指定したテンプレート
* https://github.com/masutaka/sandbox/blob/a9f91dd6d9b4611455b9a1bb230f6bf2d5db46d1/.github/workflows/templates/issue.md
* 実行した GitHub Action
* https://github.com/masutaka/sandbox/actions/runs/10842696875
* 作成された GitHub Issue
* https://github.com/masutaka/sandbox/issues/65
当初 5dc94d143fa4f04c7b292742314030d882b5ec95 は [JasonEtco/create-an-issue](https://github.com/JasonEtco/create-an-issue) Action を使いましたが、よく考えたら gh CLI で十分だったので、 0b60a3786bc3cdfa6af0831530e3b2bbfcbe526a でリファクタリングしました。
JasonEtco/create-an-issue …

GitHub Issue を作成する reusable workflow を作成する

---

.github/workflows/create_gh_issue.yml

https://github.com/route06/actions/pull/73 の改善です。
gh issue create には `--body-file` オプションがあったことに気がついたので、`--body` + `cat` から変更しました。
* サンプルコード
* https://github.com/masutaka/sandbox/blob/a3876601dbaf0071ed5b381ad16b1e2d1127f599/.github/workflows/create_issue.yml
* 実行した GitHub Action
* https://github.com/masutaka/sandbox/actions/runs/10846316799
* 作成された GitHub Issue
* https://github.com/masutaka/sandbox/issues/70
https://cli.github.com/manual/gh_issue_create

Refactor .github/workflows/create_gh_issue.yml

---

.github/workflows/create_gh_issue.yml

https://github.com/route06/actions/pull/73 の軽い修正です。
複数の `assignees` と `labels` の指定に誤りがありました。`,` の後ろにスペースを付けてはいけない。
```
$ gh issue create --title '2024/09/13 Sample TODO' --body "Hoge" --assignee 'masutaka' --label 'bug, wontfix'
Creating issue in masutaka/sandbox
could not add label: ' wontfix' not found
```
ヘルプもそう表記されていました。
```
$ gh issue create --help
(snip)
$ gh issue create --label "bug,help wanted"
$ gh issue create --label bug --label "help wanted"
$ gh issue create --assignee monalisa,hubot
(snip)
```

Fix the usage of create_gh_issue.yml

---

.github/workflows/my_release.yml
README.md

🔗 https://github.com/route06/actions/pull/66#issuecomment-2290749710
> 後から `tagpr:minor` タグをつけたため、CHANGELOGが2.2.1のままとなっている
PRのclose/reopenではtagpr jobは実行されないのか
> mainブランチへのpush jobを再実行することで再度tagpr jobを動かしてみる
>
> https://github.com/route06/actions/actions/runs/10397457019
リリース対象の PR が揃ったあとに、リリースの種類を変えるのが分かりづらかった。
[My Release](https://github.com/route06/actions/actions/workflows/my_release.yml) ワークフローを手動実行できるようにした。

Add workflow_dispatch to My Release workflow

---

.github/workflows/codeql.yml
.github/workflows/codeql_core.yml

今までは CodeQL ジョブが最大 6 個 skip され、PR ステータスを占有していました。
本 PR では実際に実行された CodeQL ジョブだけ、PR ステータスに表示されます。ただし、CodeQL ジョブが実行されなかった場合、skip ジョブが 1 つだけ表示されます。後述の「動作確認結果」をご覧下さい。
他に step 名と job 名を改善しました。commit を 1 つずつ読むと分かるかと思います。
https://github.com/masutaka/sandbox/pull/80 で動作確認した。
* Filter Paths ジョブが実行され、Perform CodeQL for ... ジョブは 1 個も実行されず skip される
* https://github.com/masutaka/sandbox/actions/runs/11046157812
* PR 上での見え方
* Filter Paths ジョブが実行され、Perform CodeQL for ... ジョブは 1 個実行される
* https://github.com/masutaka/sandbox/actions/runs/11046170531/attempts/1
* PR 上での見え方
* Filter Paths ジョブが実行され、Perform CodeQL for ... ジョブは 4 個実行される。1 つ失敗しているのは無視して大丈夫
* https://github.com/masutaka/sandbox/actions/runs/11046199493
* PR 上での見え方
* Filter Paths ジョブが実行され、Perform CodeQL for ... ジョブは最大の 6 個実行される。2 つ失敗しているのは無視して大丈夫
* …

Dynamically generate CodeQL jobs

---

.github/workflows/codeql.yml

少なくともパブリックリポジトリでは最初に GitHub Advanced Security の有効化が必要でした。
このコメントに従えば CodeQL の設定を完了させたいので、Setup を追加しました。

Add Setup to CodeQL workflow doc

---

.github/workflows/codeql.yml
.github/workflows/codeql_core.yml

CodeQL 関連 workflow だけ、ubuntu-22.04 を使っている。他の reusable workflow は全て ubuntu-latest。
* https://github.com/route06/actions/blob/v2.4.1/.github/workflows/codeql.yml#L50
* https://github.com/route06/actions/blob/v2.4.1/.github/workflows/codeql_core.yml#L21
Ubuntu のバージョンを固定して、セキュリティや信頼性を高めようとしたのだと思う。
経験上、GitHub Actions で Ubuntu バージョンを固定しなくて壊れたことはないし、自動アップデートの仕組みもないと思うので、ubuntu-latest に変更する。
大丈夫そうです。
https://github.com/masutaka/sandbox/actions/runs/11101601135
現在の ubuntu-latest は ubuntu-24.04 へのエイリアス。
https://github.com/actions/runner-images/tree/ce5aa1950d31fd67c0014160a0164005a3e7f43c
ubuntu-22.04 の End of Standard Support は 2027/04。
https://ubuntu.com/about/release-cycle

Always use ubuntu-latest

---

.github/workflows/dependency_review.yml
README.md

GitHub Advanced Security (GHAS) の Dependency Review を reusable workflow として提供します。
* 機能
* 脆弱性のあるパッケージを検知したら、ジョブが失敗する
* 感想
* CodeQL のように何分もかからない様子
* [簡単な npm パッケージ 1 つの package(-lock).json の時は、13s で完了した](https://github.com/masutaka/sandbox/actions/runs/11123475643/job/30907000167)
* `on: pull_request` のトリガーで良さそうだし、PR マージ前の必須ジョブにも出来る
* 薄いラッパーのような reusable workflow だけど、バージョンアップや timeout を考えなくてよいのはメリットだと思う
* 脆弱性のあるパッケージが見つからなかったので、ジョブが成功した
* https://github.com/masutaka/sandbox/actions/runs/11123475643
* 脆弱性のあるパッケージが見つかったので、ジョブが失敗した
* https://github.com/masutaka/sandbox/actions/runs/11123460955
* [依存関係の確認について \- GitHub Docs](https://docs.github.com/ja/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review)
* …

Introduce Dependency Review workflow

---

.github/dependabot.yml

これまで続けてきて、毎週アップデートはしなくて良い気がしたので、毎月アップデートに頻度を下げました。
See also:
https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval

Reduce the frequency of Dependabot update for GitHub Actions

---

.github/workflows/dependency_review.yml

.github/workflows/dependency_review.yml デフォルトで、PR にコメントするようにしました。
そのためにはユーザー側で permissions を設定する必要があるため、破壊的な変更とは言えないまでも、近い変更にはなっています。
Dependency Review ジョブが失敗すると CI が落ちるので気づくことはできます。
ただ、"▶Vulnerabilities" をクリックしないと分かりません。
🔗 https://github.com/masutaka/sandbox/actions/runs/13430473078/job/37521109378
一方で Summary をクリックすると分かりやすい結果を確認できることは、気づくのが難しいです。
🔗 https://github.com/masutaka/sandbox/actions/runs/13430473078
別な話として、巨大な PR では脆弱性が見つかる以外で Dependency Review ジョブが失敗することがあります。
* https://github.com/actions/dependency-review-action/issues/786
* https://github.com/actions/dependency-review-action/issues/867
こんな振る舞いだった。
1. 当該 PR で脆弱性が初めて見つかる
* Dependency Review の CI が失敗し、PR にコメントが追加される
* 例: https://github.com/masutaka/sandbox/pull/104#issuecomment-2670769586
2. PR に commit を追加した。脆弱性は修正されていない
* …

Dependency Review ジョブが失敗したら、PR にコメントする
